org: hamzayy
app: testlambda
service: serverless-test-rds
provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 30
functions:
  getPerson:
    handler: handler.getPerson
    events:
      - http:
          path: api/v1/get-person
          method: get
          cors: true
  createPerson:
    handler: handler.createPerson
    events:
      - http:
          path: api/v1/create-person
          method: post
          cors: true
plugins:
  - serverless-offline